export const projects = [
  {
    slug: "antonino",
    title: "ANTONINO",
    subtitle: "Almacén Gourmet",
    pageTitle: "Antonino — Be Management",
    metaDescription:
      "Antonino: construcción de identidad digital gourmet con redes sociales, audiovisual y desarrollo web para un almacén premium.",
    heroTags: ["Redes Sociales", "Audiovisual", "Desarrollo Web"],
    heroImage: "cliente-antonino.png",
    instagramUrl: "https://www.instagram.com/antoninocitybell/",
    instagramHandle: "@antoninocitybell",
    websiteUrl: "https://antonino.com.ar",
    websiteDomain: "antonino.com.ar",
    overviewLabel: "El Proyecto",
    overviewHeadingBefore: "Una identidad gourmet que ",
    overviewHeadingGrad: "eleva la percepción de marca",
    overviewHeadingAfter: "",
    overviewParagraphs: [
      "Antonino llegó con una propuesta gourmet de calidad pero sin una presencia digital que reflejara ese nivel. El desafío era construir una identidad visual coherente que transmitiera la sofisticación de sus productos y atrajera al cliente correcto.",
      "Construimos una estrategia de contenido orientada a la estética gourmet: fotografía de producto cuidada, reels con identidad visual definida y un sitio web que comunica la experiencia antes de la compra. Cada pieza fue diseñada para generar percepción de valor y convertir seguidores en clientes.",
      "El resultado fue una imagen de marca consolidada en redes, con mayor interacción, nuevos seguidores del perfil de cliente ideal y un sitio web que funciona como carta de presentación del negocio.",
    ],
    meta: {
      cliente: "Antonino",
      industria: "Almacén Gourmet",
      servicios: ["Redes Sociales", "Audiovisual", "Desarrollo Web"],
      año: "2024",
    },
    services: [
      { title: "Redes Sociales", description: "Gestión de Instagram con identidad visual gourmet, calendario de contenido y comunidad enfocada en el cliente ideal.", iconSvg: `<rect x="2" y="2" width="20" height="20" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1" fill="#FF6A00"/>` },
      { title: "Audiovisual", description: "Sesiones de fotografía y video de producto que comunican calidad y generan deseo de compra.", iconSvg: `<path d="M15 10l4.553-2.069A1 1 0 0121 8.82v6.36a1 1 0 01-1.447.894L15 14M3 8a2 2 0 012-2h10a2 2 0 012 2v8a2 2 0 01-2 2H5a2 2 0 01-2-2V8z"/>` },
      { title: "Desarrollo Web", description: "Sitio web con catálogo de productos, identidad de marca coherente y optimizado para dispositivos móviles.", iconSvg: `<rect x="2" y="3" width="20" height="14" rx="2"/><path d="M8 21h8M12 17v4"/>` },
    ],
    gallery: ["antonino-1.png", "antonino-2.png", "antonino-3.png"],
    relatedProjects: [
      { slug: "lo-de-jorge", title: "LO DE JORGE", tags: "Redes · Audiovisual · Web", image: "cliente-ldj.png" },
      { slug: "san-lorenzo", title: "SAN LORENZO VC", tags: "Marketing 360°", image: "cliente-slvc.png" },
    ],
  },
  {
    slug: "chiusaroli",
    title: "CHIUSAROLI",
    subtitle: "Construcción",
    pageTitle: "Chiusaroli — Be Management",
    metaDescription:
      "Chiusaroli: rebranding, comunicación digital y desarrollo web para una empresa de construcción con trayectoria.",
    heroTags: ["Comunicación", "Branding", "Desarrollo Web"],
    heroImage: "chielte-chiusaroli.png",
    instagramUrl: "https://www.instagram.com/chiusaroli.pisos/",
    instagramHandle: "@chiusaroli.pisos",
    websiteUrl: "https://chiusaroli.com.ar",
    websiteDomain: "chiusaroli.com.ar",
    overviewLabel: "El Proyecto",
    overviewHeadingBefore: "Una identidad digital que ",
    overviewHeadingGrad: "refleja años de trayectoria",
    overviewHeadingAfter: "",
    overviewParagraphs: [
      "Chiusaroli es una empresa del rubro construcción con trayectoria y experiencia, pero con una presencia digital que no comunicaba ese nivel. En un mercado donde la confianza y la solidez son todo, su imagen no estaba a la altura de su trabajo real.",
      "Desarrollamos un rebranding integral aplicado a su Instagram y sitio web: nueva identidad visual, comunicación más clara y profesional, y un sitio web que funciona como carta de presentación digital del negocio. Todo alineado a posicionar a Chiusaroli como una empresa de referencia en su rubro.",
      "El resultado fue una presencia digital más sólida y confiable, una identidad de marca consolidada y un sitio web que genera nuevas consultas de clientes que buscan calidad y respaldo en el rubro construcción.",
    ],
    meta: {
      cliente: "Chiusaroli",
      industria: "Construcción",
      servicios: ["Comunicación", "Branding", "Desarrollo Web"],
      año: "2024",
    },
    services: [
      { title: "Branding", description: "Rebranding integral: nueva identidad visual aplicada de forma consistente en todos los canales digitales de la empresa.", iconSvg: `<path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"/>` },
      { title: "Comunicación Digital", description: "Gestión de redes con contenido que comunica experiencia, calidad y confianza en el rubro construcción.", iconSvg: `<rect x="2" y="2" width="20" height="20" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1" fill="#FF6A00"/>` },
      { title: "Desarrollo Web", description: "Sitio web profesional que funciona como carta de presentación y generador de nuevas consultas para el negocio.", iconSvg: `<rect x="2" y="3" width="20" height="14" rx="2"/><path d="M8 21h8M12 17v4"/>` },
    ],
    gallery: ["chiusaroli-1.png", "chiusaroli-2.png", "chiusaroli-3.png"],
    relatedProjects: [
      { slug: "maxipiso", title: "MAXIPISO", tags: "Marketing 360°", image: "cliente-maxipiso.png" },
      { slug: "hielocity", title: "HIELO CITY", tags: "Marketing · Ads", image: "cliente-hielocity.png" },
    ],
  },
  {
    slug: "giobocco",
    title: "GIOBOCCO",
    subtitle: "Calzado Femenino",
    pageTitle: "Giobocco — Be Management",
    metaDescription:
      "Giobocco: estrategia de contenido, gestión de redes y producciones audiovisuales para una marca de calzado femenino.",
    heroTags: ["Producciones", "Gestión de Redes"],
    heroImage: "cliente-giobocco.png",
    instagramUrl: "https://www.instagram.com/giobocco_shoes/",
    instagramHandle: "@giobocco_shoes",
    websiteUrl: "https://www.giobocco.com.ar/",
    websiteDomain: "giobocco.com.ar",
    overviewLabel: "El Proyecto",
    overviewHeadingBefore: "Una marca aspiracional que ",
    overviewHeadingGrad: "convierte seguidoras en clientas",
    overviewHeadingAfter: "",
    overviewParagraphs: [
      "Giobocco es una marca de calzado femenino con un producto diferencial y una base de clientas fieles. El desafío era trasladar esa identidad de marca al mundo digital de forma efectiva, mejorando tanto la percepción de la marca como la conversión en su e-commerce.",
      "Desarrollamos una estrategia integral de contenido y gestión de redes, combinando producciones fotográficas y audiovisuales que destacan la estética y la calidad del calzado con una pauta estratégica para ampliar el alcance y llevar tráfico calificado al sitio web.",
      "El resultado fue una imagen de marca más consistente y aspiracional en redes, mayor tráfico hacia el e-commerce y un crecimiento sostenido en la comunidad de seguidoras que representan el cliente ideal de Giobocco.",
    ],
    meta: {
      cliente: "Giobocco",
      industria: "Calzado Femenino",
      servicios: ["Producciones", "Gestión de Redes"],
      año: "2024",
    },
    services: [
      { title: "Gestión de Redes", description: "Estrategia de contenido enfocada en la estética del producto y la comunidad de clientas, con publicaciones que generan deseo y fidelización.", iconSvg: `<rect x="2" y="2" width="20" height="20" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1" fill="#FF6A00"/>` },
      { title: "Producciones Audiovisuales", description: "Sesiones de foto y video que destacan la calidad y el diseño del calzado, con un resultado visual aspiracional.", iconSvg: `<path d="M15 10l4.553-2.069A1 1 0 0121 8.82v6.36a1 1 0 01-1.447.894L15 14M3 8a2 2 0 012-2h10a2 2 0 012 2v8a2 2 0 01-2 2H5a2 2 0 01-2-2V8z"/>` },
      { title: "Publicidad & Ads", description: "Campañas de pauta para ampliar el alcance y llevar tráfico calificado al e-commerce de la marca.", iconSvg: `<circle cx="12" cy="12" r="9"/><path d="M12 3a9 9 0 0 1 9 9M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>` },
    ],
    gallery: ["giobocco-1.png", "giobocco-2.png", "giobocco-3.png"],
    relatedProjects: [
      { slug: "antonino", title: "ANTONINO", tags: "Redes · Web", image: "cliente-antonino.png" },
      { slug: "lo-de-jorge", title: "LO DE JORGE", tags: "Redes · Audiovisual · Web", image: "cliente-ldj.png" },
    ],
  },
  {
    slug: "hielocity",
    title: "HIELO CITY",
    subtitle: "Producción y Distribución de Hielo",
    pageTitle: "Hielo City — Be Management",
    metaDescription:
      "Hielo City: marketing, contenido y publicidad para posicionar una marca de producción y distribución de hielo.",
    heroTags: ["Marketing", "Contenido", "Ads"],
    heroImage: "cliente-hielocity.png",
    instagramUrl: "https://www.instagram.com/hielocity",
    instagramHandle: "@hielocity",
    websiteUrl: null,
    websiteDomain: null,
    overviewLabel: "El Proyecto",
    overviewHeadingBefore: "Una presencia digital sólida que ",
    overviewHeadingGrad: "captura demanda en temporada",
    overviewHeadingAfter: "",
    overviewParagraphs: [
      "Hielo City opera en un mercado estacional de alta demanda donde la velocidad de respuesta y la visibilidad de marca son esenciales para capturar clientes en los picos de temporada. El desafío era construir una imagen profesional que diferenciara a la marca y escalara su alcance de forma sostenida.",
      "Acompañamos el crecimiento de la marca profesionalizando su imagen en redes, desarrollando contenido de valor que posicionara a Hielo City como referente en su sector y generando colaboraciones estratégicas para ampliar su comunidad en momentos clave del año.",
      "El trabajo permitió que Hielo City llegara a las temporadas de mayor demanda con una presencia digital sólida, mayor reconocimiento de marca y una comunidad activa que se convirtió en canal de ventas directo.",
    ],
    meta: {
      cliente: "Hielo City",
      industria: "Producción y Distribución de Hielo",
      servicios: ["Marketing", "Contenido", "Ads"],
      año: "2024",
    },
    services: [
      { title: "Marketing Digital", description: "Estrategia de contenido y comunidad orientada a posicionar la marca como referente en su sector y capturar demanda estacional.", iconSvg: `<rect x="2" y="2" width="20" height="20" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1" fill="#FF6A00"/>` },
      { title: "Contenido", description: "Producción de contenido que comunica los valores de la marca y genera interacción en los momentos de mayor demanda.", iconSvg: `<path d="M15 10l4.553-2.069A1 1 0 0121 8.82v6.36a1 1 0 01-1.447.894L15 14M3 8a2 2 0 012-2h10a2 2 0 012 2v8a2 2 0 01-2 2H5a2 2 0 01-2-2V8z"/>` },
      { title: "Publicidad & Ads", description: "Campañas en temporada alta para maximizar el alcance y convertir visibilidad en pedidos concretos.", iconSvg: `<circle cx="12" cy="12" r="9"/><path d="M12 3a9 9 0 0 1 9 9M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>` },
    ],
    gallery: ["hielocity-1.png", "hielocity-2.png", "hielocity-3.png"],
    relatedProjects: [
      { slug: "kaizen", title: "KAIZEN", tags: "Publicidad · Contenido", image: "cliente-kaizen.png" },
      { slug: "giobocco", title: "GIOBOCCO", tags: "Producciones · Redes", image: "cliente-giobocco.png" },
    ],
  },
  {
    slug: "kaizen",
    title: "KAIZEN",
    subtitle: "Concesionaria Honda",
    pageTitle: "Kaizen — Be Management",
    metaDescription:
      "Kaizen: publicidad, contenido y diseño para una concesionaria Honda en La Plata.",
    heroTags: ["Publicidad", "Contenido", "Diseño"],
    heroImage: "cliente-kaizen.png",
    instagramUrl: "https://www.instagram.com/kaizenmotoslaplata",
    instagramHandle: "@kaizenmotoslaplata",
    websiteUrl: null,
    websiteDomain: null,
    overviewLabel: "El Proyecto",
    overviewHeadingBefore: "Una comunicación que ",
    overviewHeadingGrad: "transmite autoridad y confianza",
    overviewHeadingAfter: "",
    overviewParagraphs: [
      "Kaizen es una concesionaria Honda en La Plata que buscaba diferenciarse en un mercado competitivo donde la claridad del mensaje y la percepción de profesionalismo son determinantes para generar consultas y visitas al local.",
      "Trabajamos el posicionamiento de marca desde un enfoque estratégico: redefinimos la comunicación en redes sociales para que reflejara la seriedad y el respaldo de la marca Honda, generamos contenido de valor para el cliente potencial y diseñamos piezas visuales que transmiten confianza y autoridad en el rubro.",
      "El resultado fue una comunicación más clara y consistente, mayor interacción en redes y una percepción de marca más profesional que acompaña el nivel de la marca que representan.",
    ],
    meta: {
      cliente: "Kaizen",
      industria: "Concesionaria Honda",
      servicios: ["Publicidad", "Contenido", "Diseño"],
      año: "2024",
    },
    services: [
      { title: "Publicidad & Ads", description: "Campañas pagadas orientadas a generar consultas y visitas al local, con segmentación por perfil de comprador ideal.", iconSvg: `<circle cx="12" cy="12" r="9"/><path d="M12 3a9 9 0 0 1 9 9M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>` },
      { title: "Contenido", description: "Producción de contenido que comunica el valor de la marca Honda y los servicios del concesionario de forma clara y atractiva.", iconSvg: `<path d="M15 10l4.553-2.069A1 1 0 0121 8.82v6.36a1 1 0 01-1.447.894L15 14M3 8a2 2 0 012-2h10a2 2 0 012 2v8a2 2 0 01-2 2H5a2 2 0 01-2-2V8z"/>` },
      { title: "Diseño", description: "Piezas visuales coherentes con la identidad de marca, aplicadas en redes y materiales de comunicación.", iconSvg: `<path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"/>` },
    ],
    gallery: ["kaizen-1.png", "kaizen-2.png", "kaizen-3.png"],
    relatedProjects: [
      { slug: "giobocco", title: "GIOBOCCO", tags: "Producciones · Redes", image: "cliente-giobocco.png" },
      { slug: "maxipiso", title: "MAXIPISO", tags: "Marketing 360°", image: "cliente-maxipiso.png" },
    ],
  },
  {
    slug: "lo-de-jorge",
    title: "LO DE JORGE",
    subtitle: "Gastronomía — Parrilla Restó",
    pageTitle: "Lo De Jorge — Be Management",
    metaDescription:
      "Lo De Jorge: estrategia integral de redes sociales, producción audiovisual y desarrollo web para posicionar una parrilla restó como referente de zona.",
    heroTags: ["Redes Sociales", "Audiovisual", "Desarrollo Web"],
    heroImage: "cliente-ldj.png",
    instagramUrl: "https://www.instagram.com/lodejorge.ldj/",
    instagramHandle: "@lodejorge.ldj",
    websiteUrl: "https://lodejorge.com/",
    websiteDomain: "lodejorge.com",
    overviewLabel: "El Proyecto",
    overviewHeadingBefore: "Una parrilla que se convirtió en ",
    overviewHeadingGrad: "referente de su zona",
    overviewHeadingAfter: "",
    overviewParagraphs: [
      "Lo De Jorge llegó a nosotros con una propuesta gastronómica sólida pero una presencia digital incipiente. El desafío era claro: trasladar la calidez y la calidad del local a todos los canales digitales, construyendo una marca que generara deseo antes de que el cliente pusiera un pie adentro del restó.",
      "Desarrollamos una estrategia integral que combinó producción audiovisual de alta calidad, gestión de redes sociales con identidad visual consistente y el desarrollo de un sitio web diseñado para convertir visitas en reservas. Cada pieza de contenido fue pensada para mostrar lo que diferencia a Lo De Jorge: el fuego, la materia prima y el ambiente que hace que la gente vuelva.",
      "El resultado fue un crecimiento sostenido en visibilidad orgánica, un aumento real en las consultas por reservas a través de los canales digitales y el posicionamiento de la marca como una de las parrillas de referencia en su zona. Hoy, Lo De Jorge tiene una identidad digital tan potente como su propuesta gastronómica.",
    ],
    meta: {
      cliente: "Lo De Jorge",
      industria: "Gastronomía — Parrilla Restó",
      servicios: ["Redes Sociales", "Audiovisual", "Desarrollo Web"],
      año: "2024",
    },
    services: [
      { title: "Redes Sociales", description: "Gestión integral de Instagram con contenido estratégico, calendario editorial y comunidad activa que genera interacción y nuevos clientes de forma consistente.", iconSvg: `<rect x="2" y="2" width="20" height="20" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1" fill="#FF6A00"/>` },
      { title: "Audiovisual", description: "Producción de fotos y videos profesionales que capturan la esencia del fuego y la cocina. Reels, historias y contenido que genera deseo antes de la primera visita.", iconSvg: `<path d="M15 10l4.553-2.069A1 1 0 0121 8.82v6.36a1 1 0 01-1.447.894L15 14M3 8a2 2 0 012-2h10a2 2 0 012 2v8a2 2 0 01-2 2H5a2 2 0 01-2-2V8z"/>` },
      { title: "Desarrollo Web", description: "Diseño y desarrollo de un sitio web orientado a la conversión, con menú digital, formulario de reservas y optimización para buscadores.", iconSvg: `<rect x="2" y="3" width="20" height="14" rx="2"/><path d="M8 21h8M12 17v4"/>` },
    ],
    gallery: ["ldj-1.webp", "ldj-2.png", "ldj-3.png", "ldj-4.png"],
    relatedProjects: [
      { slug: "antonino", title: "ANTONINO", tags: "Redes · Web", image: "cliente-antonino.png" },
      { slug: "san-lorenzo", title: "SAN LORENZO VC", tags: "Marketing 360°", image: "cliente-slvc.png" },
    ],
  },
  {
    slug: "maxipiso",
    title: "MAXIPISO",
    subtitle: "Mayorista / Construcción",
    pageTitle: "MaxiPiso — Be Management",
    metaDescription:
      "MaxiPiso: Marketing 360° para mayorista de materiales de construcción. Ecosistema digital, redes, web y publicidad.",
    heroTags: ["Marketing 360°"],
    heroImage: "cliente-maxipiso.png",
    instagramUrl: "https://www.instagram.com/maxipiso.mayorista",
    instagramHandle: "@maxipiso.mayorista",
    websiteUrl: "https://maxipiso.com.ar",
    websiteDomain: "maxipiso.com.ar",
    overviewLabel: "El Proyecto",
    overviewHeadingBefore: "Un ecosistema digital que ",
    overviewHeadingGrad: "acompaña el ritmo del negocio",
    overviewHeadingAfter: "",
    overviewParagraphs: [
      "MaxiPiso opera en el rubro mayorista de materiales de construcción, un mercado competitivo donde la visibilidad y la confianza son claves para cerrar ventas de volumen. Cuando llegaron a nosotros, tenían presencia digital dispersa y una comunicación que no reflejaba la escala real del negocio.",
      "Trabajamos un enfoque de Marketing 360° para construir desde cero su ecosistema de ventas digital: rediseño de identidad visual, gestión de redes orientada a captar revendedores y clientes mayoristas, desarrollo web con catálogo y formulario de cotización, y campañas de publicidad para escalar el alcance.",
      "El trabajo generó un posicionamiento más sólido en su rubro, mayor volumen de consultas entrantes y una imagen de marca que comunica escala, confianza y profesionalismo. Hoy MaxiPiso tiene un ecosistema digital que acompaña el ritmo de su negocio.",
    ],
    meta: {
      cliente: "MaxiPiso",
      industria: "Mayorista / Construcción",
      servicios: ["Marketing 360°"],
      año: "2024",
    },
    services: [
      { title: "Marketing Digital", description: "Gestión de redes orientada a captar revendedores y clientes de volumen, con contenido que comunica escala y confianza.", iconSvg: `<rect x="2" y="2" width="20" height="20" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1" fill="#FF6A00"/>` },
      { title: "Desarrollo Web", description: "Sitio web con catálogo de productos, formulario de cotización y diseño orientado a la conversión mayorista.", iconSvg: `<rect x="2" y="3" width="20" height="14" rx="2"/><path d="M8 21h8M12 17v4"/>` },
      { title: "Publicidad & Ads", description: "Campañas pagadas en Meta para ampliar el alcance hacia el perfil de cliente mayorista ideal.", iconSvg: `<circle cx="12" cy="12" r="9"/><path d="M12 3a9 9 0 0 1 9 9M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>` },
    ],
    gallery: ["maxipiso-1.png", "maxipiso-2.png", "maxipiso-3.png"],
    relatedProjects: [
      { slug: "lo-de-jorge", title: "LO DE JORGE", tags: "Redes · Audiovisual · Web", image: "cliente-ldj.png" },
      { slug: "san-lorenzo", title: "SAN LORENZO VC", tags: "Marketing 360°", image: "cliente-slvc.png" },
    ],
  },
  {
    slug: "san-lorenzo",
    title: "SAN LORENZO DE VILLA CASTELLS",
    subtitle: "Club Deportivo",
    pageTitle: "San Lorenzo de Villa Castells — Be Management",
    metaDescription:
      "San Lorenzo de Villa Castells: Marketing 360° para profesionalizar la imagen digital de un club deportivo con historia.",
    heroTags: ["Marketing 360°"],
    heroImage: "cliente-slvc.png",
    instagramUrl: "https://www.instagram.com/slvc.oficial",
    instagramHandle: "@slvc.oficial",
    websiteUrl: "https://slvcoficial.com",
    websiteDomain: "slvcoficial.com",
    overviewLabel: "El Proyecto",
    overviewHeadingBefore: "Una presencia digital ",
    overviewHeadingGrad: "a la altura de su historia",
    overviewHeadingAfter: "",
    overviewParagraphs: [
      "San Lorenzo de Villa Castells es un club con historia, comunidad y una propuesta deportiva sólida. Sin embargo, su comunicación digital no transmitía ese peso institucional. Llegaron a nosotros con la necesidad de profesionalizar su imagen y conectar mejor con sus socios, jugadores y la comunidad local.",
      "Implementamos una estrategia de Marketing 360° que abarcó desde el rediseño de su comunicación en redes sociales hasta la gestión de contenido institucional, cobertura de partidos y eventos, y desarrollo de materiales visuales que fortalecieran la identidad del club.",
      "Hoy San Lorenzo de Villa Castells tiene una presencia digital que está a la altura de su historia: coherente, activa y con un vínculo más fuerte con su comunidad. La percepción del club creció tanto entre los socios actuales como entre los potenciales.",
    ],
    meta: {
      cliente: "San Lorenzo de Villa Castells",
      industria: "Club Deportivo",
      servicios: ["Marketing 360°"],
      año: "2024",
    },
    services: [
      { title: "Gestión de Redes", description: "Comunicación institucional y deportiva con calendario editorial, cobertura de partidos y contenido que conecta con la comunidad del club.", iconSvg: `<rect x="2" y="2" width="20" height="20" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1" fill="#FF6A00"/>` },
      { title: "Producción de Contenido", description: "Fotografía y video de partidos, entrenamientos y eventos institucionales que documentan la vida del club.", iconSvg: `<path d="M15 10l4.553-2.069A1 1 0 0121 8.82v6.36a1 1 0 01-1.447.894L15 14M3 8a2 2 0 012-2h10a2 2 0 012 2v8a2 2 0 01-2 2H5a2 2 0 01-2-2V8z"/>` },
      { title: "Estrategia de Marca", description: "Definición y aplicación consistente de la identidad visual del club en todos los canales digitales.", iconSvg: `<path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"/>` },
    ],
    gallery: ["slvc-1.png", "slvc-2.png", "slvc-3.png"],
    relatedProjects: [
      { slug: "maxipiso", title: "MAXIPISO", tags: "Marketing 360°", image: "cliente-maxipiso.png" },
      { slug: "antonino", title: "ANTONINO", tags: "Redes · Web", image: "cliente-antonino.png" },
    ],
  },
];

export const projectCards = [
  { slug: "lo-de-jorge", title: "Lo de Jorge", subtitle: "Parrilla Restó", image: "cliente-ldj.png", tags: ["Redes", "Audiovisual", "Desarrollo Web"], dataTags: "redes,audiovisual,desarrollo-web" },
  { slug: "antonino", title: "Antonino", subtitle: "Almacén de Fiambres", image: "cliente-antonino.png", tags: ["Redes", "Desarrollo Web"], dataTags: "redes,desarrollo-web" },
  { slug: "san-lorenzo", title: "San Lorenzo VC", subtitle: "Club de Fútbol", image: "cliente-slvc.png", tags: ["Marketing 360°"], dataTags: "marketing-360" },
  { slug: "maxipiso", title: "MaxiPiso", subtitle: "Líder Mayorista", image: "cliente-maxipiso.png", tags: ["Marketing 360°"], dataTags: "marketing-360" },
  { slug: "giobocco", title: "Giobocco", subtitle: "Calzado Femenino", image: "cliente-giobocco.png", tags: ["Producciones", "Gestión de Redes"], dataTags: "redes,audiovisual" },
  { slug: "kaizen", title: "Kaizen", subtitle: "Concesionaria Honda", image: "cliente-kaizen.png", tags: ["Publicidad", "Contenido", "Diseño"], dataTags: "redes,audiovisual" },
  { slug: "hielocity", title: "Hielo City", subtitle: "Producción y Distribución de Hielo", image: "cliente-hielocity.png", tags: ["Marketing", "Contenido", "Ads"], dataTags: "redes,marketing-360" },
  { slug: "chiusaroli", title: "Chiusaroli", subtitle: "Construcción", image: "chielte-chiusaroli.png", tags: ["Comunicación", "Branding", "Desarrollo Web"], dataTags: "redes,desarrollo-web" },
];

export function getProject(slug) {
  return projects.find((p) => p.slug === slug);
}

export function getAllSlugs() {
  return projects.map((p) => ({ slug: p.slug }));
}
